export const cartActionsConstants = {
  ADD_TO_CART: "ADD_TO_CART",
  ADD_TO_CART_FAILED: "ADD_TO_CART_FAILED",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  REMOVE_FROM_CART_FAILED: "REMOVE_FROM_CART_FAILED",
  DECREMENT_CART_ITEM: "DECREMENT_CART_ITEM",
  DECREMENT_CART_ITEM_FAILED: "DECREMENT_CART_ITEM_FAILED",
  INCREMENT_CART_ITEM: "INCREMENT_CART_ITEM",
  INCREMENT_CART_ITEM_FAILED: "INCREMENT_CART_ITEM_FAILED",
};
