export const cartConstants = {
  GET_CART: "GET_CART",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  DECREMENT_CART_ITEM: "DECREMENT_CART_ITEM",
  INCREMENT_CART_ITEM: "INCREMENT_CART_ITEM",
  CART_LOADING: "CART_LOADING",
  CART_ERROR: "CART_ERROR",
  CLEAR_CART: "CLEAR_CART",
};

export const wishlistConstants = {
  GET_WISHLIST: "GET_WISHLIST",
  ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
  REMOVE_FROM_WISHLIST: "REMOVE_FROM_WISHLIST",
  WISHLIST_LOADING: "WISHLIST_LOADING",
};

export const addressConstants = {
  GET_ADDRESSES: "GET_ADDRESSES",
  ADD_ADDRESS: "ADD_ADDRESS",
  UPDATE_ADDRESS: "UPDATE_ADDRESS",
  REMOVE_ADDRESS: "REMOVE_ADDRESS",
  ADDRESS_LOADING: "ADDRESS_LOADING",
};

export const orderConstants = {
  ORDER_LOADING: "ORDER_LOADING",
  GET_ORDERS: "GET_ORDERS",
  ORDER_ERROR: "ORDER_ERROR",
};
