export const wishlistActionsConstants = {
  ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
  ADD_TO_WISHLIST_FAILED: "ADD_TO_WISHLIST_FAILED",
  REMOVE_FROM_WISHLIST: "REMOVE_FROM_WISHLIST",
  REMOVE_FROM_WISHLIST_FAILED: "REMOVE_FROM_WISHLIST_FAILED",
};
